baseurl = "https://www.kanthi.in/"
languageCode = "en-us"
title = "K.I.N.G."
theme="slim"

[params]
  Subtitle = "King Is No Geek"
  GithubID = "kanthi"
  TwitterID = "nkanthi"
  AnalyticsID = "UA-72350566-1"
  DisqusShortname = "nkanthikiran"
  Summary = false  # takes true or false
  Content = false  # takes true or false
  # if both are set to true, summary is shown.
  FooterMsg = "Copyright K.I.N.G 2017 "
